pipeline {
    agent any
    environment {
        AZURE_CLIENT_ID = credentials('azure-jenkins-clinet-id')
        AZURE_SECRET_VALUE = credentials('azure-jerkins-secret-value')
        AZURE_TENANT_ID = credentials('azure-jenkins-tenant-id')
    }
    stages {
        stage('Azure-Deploy') {
            agent {
                docker {
                    image 'sarthakbanerjee/custom-terraform-azure-image:1'
                    args "--entrypoint=''"
                }
            }
            steps {
                echo 'Deploy Azure Stack'
//Either of the block to be executed for creation or deletion of stack
                    sh '''
                        az --version
                        terraform --version
                        az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_SECRET_VALUE --tenant $AZURE_TENANT_ID
                        cd terraform-resource
                        terraform init
                        terraform plan
                        terraform apply --auto-approve    
                    '''
                    // sh '''
                    //     terraform destroy --auto-approve
                    // '''
            }
        }
    }
}